-- MySQL Script generated by MySQL Workbench
-- dom 21 oct 2018 16:56:00 CEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema TheChoose_mvc
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema TheChoose_mvc
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TheChoose_mvc` DEFAULT CHARACTER SET utf8 ;
USE `TheChoose_mvc` ;

-- -----------------------------------------------------
-- Table `TheChoose_mvc`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheChoose_mvc`.`usuarios` (
  `email` VARCHAR(255) NOT NULL,
  `nombreCompleto` VARCHAR(255) NOT NULL,
  `passwd` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`email`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheChoose_mvc`.`encuestas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheChoose_mvc`.`encuestas` (
  `idEncuesta` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NULL,
  `link` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEncuesta`),
  CONSTRAINT `fk_encuestas_1`
    FOREIGN KEY (`email`)
    REFERENCES `TheChoose_mvc`.`usuarios` (`email`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE UNIQUE INDEX `link_UNIQUE` ON `TheChoose_mvc`.`encuestas` (`link` ASC);

CREATE INDEX `fk_encuestas_1_idx` ON `TheChoose_mvc`.`encuestas` (`email` ASC);


-- -----------------------------------------------------
-- Table `TheChoose_mvc`.`participaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheChoose_mvc`.`participaciones` (
  `idEncuesta` INT NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idEncuesta`, `email`),
  CONSTRAINT `fk_participaciones_1`
    FOREIGN KEY (`idEncuesta`)
    REFERENCES `TheChoose_mvc`.`encuestas` (`idEncuesta`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_participaciones_2`
    FOREIGN KEY (`email`)
    REFERENCES `TheChoose_mvc`.`usuarios` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_participaciones_2_idx` ON `TheChoose_mvc`.`participaciones` (`email` ASC);


-- -----------------------------------------------------
-- Table `TheChoose_mvc`.`huecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheChoose_mvc`.`huecos` (
  `idEncuesta` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `horaFin` TIME NOT NULL,
  PRIMARY KEY (`idEncuesta`, `fecha`, `horaInicio`),
  CONSTRAINT `fk_huecos_1`
    FOREIGN KEY (`idEncuesta`)
    REFERENCES `TheChoose_mvc`.`encuestas` (`idEncuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `TheChoose_mvc`.`seleccionados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `TheChoose_mvc`.`seleccionados` (
  `idEncuesta` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `horaInicio` TIME NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `seleccion` TINYINT NOT NULL,
  PRIMARY KEY (`idEncuesta`, `fecha`, `horaInicio`, `email`, `seleccion`),
  CONSTRAINT `fk_seleccionados_1`
    FOREIGN KEY (`idEncuesta` , `fecha` , `horaInicio`)
    REFERENCES `TheChoose_mvc`.`huecos` (`idEncuesta` , `fecha` , `horaInicio`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_seleccionados_2`
    FOREIGN KEY (`email`)
    REFERENCES `TheChoose_mvc`.`usuarios` (`email`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_seleccionados_2_idx` ON `TheChoose_mvc`.`seleccionados` (`email` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
